### ISSUE TITLE
which files are finally needed?

### ISSUE THREAD

**Issue by danshu** [diegocambuy/CAT#2]
Hi,

After installation, I have several files under "documentation" directory and I seems that I only need the following four files:
gi_taxid_prot.dmp names.dmp nodes.dmp nr.dmnd
For other files:
nr.faa gc.prt merged.dmp gencode.dmp division.dmp delnodes.dmp citations.dmp
Can I just delete them?

Best,
Quan

**Comment by danshu** [comment]
Another question is: what is the file "nr.faa"? 

I downloaded nr.gz from "ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz" and then "gunzip" and changed   its name to "nr.faa".
I have the following error after running diamond for about half an hour:
"Error: Invalid character (-/45) in sequence"

**Comment by diegocambuy** [comment]
The nr.faa file is a fasta file with all proteins from the nr database, it
is needed at first so you can have the nr.dmnd file (which is used for
blast), so you can delete it later.

 gc.prt merged.dmp gencode.dmp division.dmp delnodes.dmp citations.dmp,
didn`t have to be downloaded, so you can also get rid of them.


2016-11-03 9:52 GMT+01:00 danshu <notifications@github.com>:

**Comment by danshu** [comment]
Thanks. If nr.faa is "ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz", why do I have this error:
"Error: Invalid character (-/45) in sequence"?

**Comment by diegocambuy** [comment]
This is a diamond/NCBI error, so not CAT. My  personal experience shows
that the nr.faa from ncbi has some truncated sequences causing headers of
the proteins to appear in the middle of the sequence. I might try to write
a code to solve that.



There is a forum here that tries to solve it

https://github.com/bbuchfink/diamond/issues/25





2016-11-03 13:48 GMT+01:00 danshu <notifications@github.com>:

**Comment by danshu** [comment]
Thanks!

**Comment by danshu** [comment]
To those who may be interested,

I run "grep -v ">" nr.faa | grep "-" > test.out" and found that there are several sequence lines starting with "-". Then I replaced these "-" with "X" by "sed 's/^-/X/g'" and then I can run "diamond makedb" without errors.
