### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by danshu** [diegocambuy/CAT#3]
Hi,

I run CAT and have the following error:

"Warning:  Sequence is long (max 32000000 for training).
Training on the first 32000000 bases.

diamond file is /path_to/target.fa_contigs_prodigal.m8
gff file is /path_to/target.fa_contigs_prodigal.gff
faa file is /path_to/target.fa_contigs_prodigal.faa
bitscore 1 is 0.9
bitscore 2 is 0.5
Traceback (most recent call last):
  File "/tools/analysis/metagenomics/CAT-master/CAT/bin/contig_id.py", line 109, in <module>
    protein=line[1].split("|")[1]
IndexError: list index out of range
running prodigal
running diamond search"

1. the first message is showing that sequence is long. But in my fasta file, "sum = 332021388, n = 37221, ave = 8920.27, largest = 27143". Is this warning due to that the total file size is larger than 32000000 bases?

2. For the "IndexError: list index out of range" error, I have checked the diamond file and here are several lines:
"1_5     ACA64215.1      45.3    75      40      1       10      83      283     357     8.4e-05 55.5
1_5     WP_059303418.1  37.8    74      46      0       13      86      319     392     1.1e-04 55.1
1_5     SCF81904.1      40.5    84      48      1       4       85      543     626     1.1e-04 55.1"
For the corresponding codes:
"all_pro=open(diamond,'r')
for line in all_pro:
  line=line.strip()
  line=line.split("\t") 
  protein=line[1].split("|")[1]
  d_allpro[protein]=True "
The cause of this error should be that there is no "|“ in protein ids. How can I solve this?

Best,
Quan

**Comment by danshu** [comment]
As far as I can understand, the cause of this problem is that, CAT expects the sequences ids in nr.faa to contain gi separated by "|", while actually these ids are accession.version now. "gi_taxid_prot.dmp" seems to be a mapping file mapping each gi to a taxid. The solution may be using an updated mapping file which maps accessions to taxid, am I correct?

**Comment by danshu** [comment]
Update:
I solved it by changing "line[1].split("|")[1]" to "line[1]" in contig_id.py and used a new mapping file:
wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz
gunzip ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz
cut -f2-3 prot.accession2taxid > gi_taxid_prot.dmp

**Comment by diegocambuy** [comment]
Yes. CAT uses the gi, so gi2taxid file and not the the
prot.accession2taxid. A new version where the access
is considered is coming. Thanks for the contribution.

2016-11-07 6:13 GMT+01:00 danshu <notifications@github.com>:
